import { sygnet } from './sygnet'
import {
  cilScrubber,
  cilApplicationsSettings,
  cilSpeedometer,
  cilSun,
  cilMoon,
  cilLockLocked,
  cilUser,
  cilAt,
  cilLibraryBuilding,
  cilDescription,
  cilTag,
  cilBookmark,
  cilLayers,
  cilDollar,
  cilCalendar,
  cilShieldAlt,
  cilTrash,
  cilStorage,
  cilMemory,
  cilOptions,
  cilFindInPage,
  cilListRich,
  cilArrowLeft,
  cilBell,
  cilEnvelopeOpen,
  cilPenAlt,
  cilSync,
  cilEuro,
  cilFlagAlt,
  cilChevronLeft
} from '@coreui/icons/js/free'

export const icons = Object.assign({}, {
  sygnet
}, {
  cilScrubber,
  cilAt,
  cilUser,
  cilLockLocked,
  cilApplicationsSettings,
  cilSpeedometer,
  cilSun,
  cilMoon,
  cilLibraryBuilding,
  cilDescription,
  cilTag,
  cilBookmark,
  cilLayers,
  cilDollar,
  cilCalendar,
  cilShieldAlt,
  cilTrash,
  cilStorage,
  cilMemory,
  cilOptions,
  cilFindInPage,
  cilListRich,
  cilArrowLeft,
  cilBell,
  cilEnvelopeOpen,
  cilPenAlt,
  cilSync,
  cilEuro,
  cilFlagAlt,
  cilChevronLeft
})
